# Generated by Django 3.2.16 on 2022-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
