# Generated by Django 3.2.16 on 2022-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_auto_20221122_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
