# Generated by Django 3.2.16 on 2022-11-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_alter_applicant_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='file',
        ),
    ]
